/* Generated by tools/generate-daemun-icons.mjs. */
import { useId } from "react";

function normalizeId(id) {
  return String(id).replace(/[^A-Za-z0-9_-]/g, "");
}

export default function DaemunIcon({
  className = "w-full h-full",
  end = "#0072ce",
  foreground = "#ffffff",
  start = "#6ed7ff",
  svgRef = null,
  title = "Daemun",
}) {
  const gradientId = `daemun-icon-gradient-${normalizeId(useId())}`;

  return (
    <svg
      ref={svgRef}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 1024 1024"
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : true}
      aria-label={title || undefined}
      className={className}
    >
      {title ? <title>{title}</title> : null}
      <defs>
        <linearGradient id={gradientId} x1="184" y1="184" x2="840" y2="840" gradientUnits="userSpaceOnUse">
          <stop offset="0" stopColor={start} />
          <stop offset="1" stopColor={end} />
        </linearGradient>
      </defs>
      <rect x="96" y="96" width="832" height="832" rx="196" fill={`url(#${gradientId})`} />
      <g fill={foreground} clipRule="evenodd">
        <path d="M240 438c80-9 118-62 146-120 46 34 206 34 252 0 28 58 66 111 146 120-8 60-58 94-116 74-55-19-103-28-156-28s-101 9-156 28c-58 20-108-14-116-74Z"/>
        <path d="M324 482c98 32 278 32 376 0l-18 52c-98 30-242 30-340 0l-18-52Z" opacity=".92"/>
        <path d="M286 548h452v62h-34v206h-74V610H394v206h-74V610h-34v-62Z"/>
        <path fillRule="evenodd" d="M414 632h196v200H414V632Zm86 0h24v200h-24V632Zm-45 39h19v124h-19V671Zm95 0h19v124h-19V671Zm-65 74a15 15 0 1 0 0 30 15 15 0 0 0 0-30Zm54 0a15 15 0 1 0 0 30 15 15 0 0 0 0-30Z"/>
        <path d="M364 850h296c-30-36-82-58-148-58s-118 22-148 58Z"/>
      </g>
    </svg>
  );
}
