---
# For configuration options and examples, please see:
# https://github.com/Clickin/Daemun/tree/main/docs/configs/settings.md

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
