# syntax = docker/dockerfile:latest
FROM docker.io/node:26-alpine

WORKDIR /app

COPY --link package.json pnpm-lock.yaml* pnpm-workspace.yaml* ./

RUN <<EOF
    set -xe
    apk add --virtual .gyp python3 make g++
    npm install -g pnpm@10.32.1
EOF

RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store pnpm fetch | grep -v "cross-device link not permitted\|Falling back to copying packages from store"

RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store pnpm install -r --offline

COPY . .

CMD ["pnpm", "run", "dev"]
