image:
  repository: k3d-registry.localhost:55000/daemun
  tag: local
  pullPolicy: Always

config:
  bookmarks:
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services:
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Daemun is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Daemun is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Daemun is awesome
  widgets:
    # show the kubernetes widget, with the cluster summary and individual nodes
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  kubernetes:
    mode: cluster
  docker:
  settings:

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "daemun.k3d.localhost:8080"

serviceAccount:
  create: true
  name: daemun

enableRbac: true

ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Daemun"
      gethomepage.dev/description: "Dynamically Detected Daemun"
      gethomepage.dev/group: "Dynamic"
      gethomepage.dev/icon: "homepage.png"
    hosts:
      - host: daemun.k3d.localhost
        paths:
          - path: /
            pathType: Prefix
