worker_processes auto;
pid /run/nginx/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  charset utf-8;

  access_log /dev/stdout;
  error_log /dev/stderr warn;
  server_tokens off;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  gzip on;
  gzip_types
    application/javascript
    application/json
    application/manifest+json
    image/svg+xml
    text/css
    text/javascript
    text/plain
    text/xml;

  upstream daemun_api {
    server unix:/run/daemun/daemun.sock;
    keepalive 32;
  }

  server {
    listen 80;
    server_name _;

    root /app/public;
    client_max_body_size 0;

    location = / {
      root /tmp/daemun/ssg;
      add_header Cache-Control "no-cache" always;
      try_files /index.html @daemun_api;
    }

    location = /index.html {
      root /tmp/daemun/ssg;
      add_header Cache-Control "no-cache" always;
      try_files /index.html @daemun_api;
    }

    location /assets/ {
      alias /app/dist/client/assets/;
      access_log off;
      add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /locales/ {
      alias /app/public/locales/;
      add_header Cache-Control "public, max-age=3600";
    }

    location /api/ {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host 127.0.0.1:3000;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://daemun_api;
    }

    location @daemun_api {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host 127.0.0.1:3000;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://daemun_api;
    }

    location = /browserconfig.xml {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host 127.0.0.1:3000;
      proxy_pass http://daemun_api;
    }

    location = /robots.txt {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host 127.0.0.1:3000;
      proxy_pass http://daemun_api;
    }

    location = /site.webmanifest {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host 127.0.0.1:3000;
      proxy_pass http://daemun_api;
    }

    location / {
      try_files $uri =404;
    }
  }
}
